name: CI

on:
  push:
    branches: [ master ]

env:
  TARGET_DIR: target
jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Prepare directory
      run: |
        echo "::set-env name=TEMP_DIR::$(mktemp -d)"
        echo "::set-env name=BRANCH_NAME::${GITHUB_REF:11}"
    
    - name: Check exported variable
      run: |
        echo "${TEMP_DIR}"
        mkdir -p "${BRANCH_NAME}"
        mkdir -p "${TEMP_DIR}/${BRANCH_NAME}/${TARGET_DIR}"
