name: CI

on:
  push:
    branches: [ master ]

env:
  TARGET_DIR: target
jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Prepare directory
      run: |
        echo "::set-env name=ARTIFACT_DIR::temp/${GITHUB_REF:11}/${TARGET_DIR}"
        echo "${ARTIFACT_DIR}"
        mkdir -p "${ARTIFACT_DIR}"
    
    - name: Check exported variable
      run: |
        echo "${ARTIFACT_DIR}"
        mkdir -p "${ARTIFACT_DIR}"
