name: CI

on:
  push

env:
  TARGET_DIR: target
jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Prepare directory
      run: |
        echo "::set-env name=TEMP_DIR::$(mktemp -d)"

    - name: Export git branch name
      run: |
        echo "::set-env name=BRANCH_NAME::${GITHUB_REF:11}"

    - name: Determine blob container name
      run: |
        if [ "${BRANCH_NAME}" = "master" ]; then
          echo "::set-env name=BLOB_NAME::bundles"
        else
          echo "::set-env name=BLOB_NAME::branchbundles"
        fi

    - name: Check exported variable
      run: |
        echo "${TEMP_DIR}"
        echo "${BRANCH_NAME}"
        echo "${BLOB_NAME}"
        mkdir -p "${TEMP_DIR}/${BRANCH_NAME}/${TARGET_DIR}"
